swagger: '2.0'
info:
  version: 1.0.0
  title: Sabre Dev Studio REST APIs
  description: "[Sabre Dev Studio](https://developer.sabre.com/io-docs) REST APIs."
  license:
    name: Sabre
    url: https://developer.sabre.com/Terms_of_Use
host: api.test.sabre.com
basePath: "/"
securityDefinitions:
  Authorization:
    type: apiKey
    description: ''
    name: Authorization
    in: header
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  "/v1/lists/supported/countries":
    get:
      description: Retrieves a list of origin and destination country codes that can
        be used to filter applicable REST Air Shopping APIs.
      summary: countries_lookup
      tags:
      - Air_Utility
      operationId: V1ListsSupportedCountriesGet
      produces:
      - application/json
      parameters:
      - name: pointofsalecountry
        in: query
        required: false
        type: string
        description: 2-letter country code of the point of sale
      responses:
        '200':
          description: successful operation
          schema:
            "$ref": "#/definitions/Countries"
          examples: {}
        '400':
          description: Invalid status value
          schema: {}
        '401':
          description: You do not have necessary permissions for the resource
          schema: {}
      security:
      - Authorization: []
  "/v1/lists/supported/historical/seasonality/airports":
    get:
      description: "Heads up – this API is powered by the Travel Insight Engine.
      For the full list of city pairs available in the test environment and in
      production view the Travel Seasonality Airports Lookup Supplemental API.
      Retrieves destinations supported by Travel Seasonality API.
      Destinations are airport codes or city codes."
      tags:
      - Air_Utility
      operationId: V1ListsSupportedHistoricalSeasonalityAirportsGet
      produces:
      - application/json
      parameters:
      - name: country
        in: query
        required: false
        type: string
        description: 2-letter ISO country code
      - name: region
        in: query
        required: false
        type: string
        enum:
            - Africa
            - Asia Pacific
            - Europe
            - Latin America
            - Middle East
            - North America
        description: Region
      responses:
        '200':
          description: successful operation
          schema:
            "$ref": "#/definitions/TravelSeasonalityDestinations"
          examples: {}
        '400':
          description: Invalid status value
          schema: {}
        '401':
          description: You do not have necessary permissions for the resource
          schema: {}
      security:
      - Authorization: []
  "/v1/lists/supported/pointofsalecountries":
    get:
      description: Returns a list of supported point of sale country codes and associated country names.
      tags:
      - Air_Utility
      operationId: V1ListsSupportedPointofsalecountriesGet
      produces:
      - application/json
      responses:
        '200':
          description: successful operation
          schema:
            "$ref": "#/definitions/Pointofsalecountries"
          examples: {}
        '400':
          description: Invalid status value
          schema: {}
        '401':
          description: You do not have necessary permissions for the resource
          schema: {}
      security:
      - Authorization: []
  "/v1/lists/supported/shop/flights/origins-destinations":
    get:
      description: "Retrieves city pairs supported by REST Air Shopping APIs. City pairs are combinations of origin and destination airport codes."
      tags:
      - Air_Utility
      operationId: V1ListsSupportedShopFlightsOriginsdestinationsGet
      produces:
      - application/json
      parameters:
      - name: origincountry
        in: query
        required: false
        type: string
        description: 2-letter ISO country code
      - name: destinationcountry
        in: query
        required: false
        type: string
        description: 2-letter ISO country code
      - name: originregion
        in: query
        required: false
        type: string
        enum:
            - Africa
            - Asia Pacific
            - Europe
            - Latin America
            - Middle East
            - North America
        description: Region
      - name: destinationregion
        in: query
        required: false
        type: string
        enum:
            - Africa
            - Asia Pacific
            - Europe
            - Latin America
            - Middle East
            - North America
        description: Region
      - name: pointofsalecountry
        in: query
        required: false
        type: string
        description: 2-letter country code of the point of sale
      responses:
        '200':
          description: successful operation
          schema:
            "$ref": "#/definitions/CityPairOriginsdestinations"
          examples: {}
        '400':
          description: Invalid status value
          schema: {}
        '401':
          description: You do not have necessary permissions for the resource
          schema: {}
      security:
      - Authorization: []
  "/v1/lists/supported/forecast/flights/origins-destinations":
    get:
      description: "Heads up – this API is powered by the Travel Insight Engine.
      For the full list of city pairs available in the
      test environment and in production view the City Pairs Supplemental API. .
      Retrieves city pairs supported by Low Fare Forecast API.
      City pairs are combinations of origin and destination airport codes."
      tags:
      - Air_Utility
      operationId: V1ListsSupportedForecastFlightsOriginsdestinationsGet
      produces:
      - application/json
      parameters:
      - name: origincountry
        in: query
        required: false
        type: string
        description: 2-letter ISO country code
      - name: destinationcountry
        in: query
        required: false
        type: string
        description: 2-letter ISO country code
      - name: originregion
        in: query
        required: false
        type: string
        enum:
            - Africa
            - Asia Pacific
            - Europe
            - Latin America
            - Middle East
            - North America
        description: Region
      - name: destinationregion
        in: query
        required: false
        type: string
        enum:
            - Africa
            - Asia Pacific
            - Europe
            - Latin America
            - Middle East
            - North America
        description: Region
      responses:
        '200':
          description: successful operation
          schema:
            "$ref": "#/definitions/CityPairOriginsdestinations"
          examples: {}
        '400':
          description: Invalid status value
          schema: {}
        '401':
          description: You do not have necessary permissions for the resource
          schema: {}
      security:
      - Authorization: []

definitions:
  Pointofsalecountries:
    title: Pointofsalecountries
    type: object
    properties:
      Countries:
        description: ''
        type: array
        items:
          "$ref": "#/definitions/Country"
      Links:
        description: ''
        type: array
        items:
          "$ref": "#/definitions/Link"
  TravelSeasonalityDestinations:
    title: TravelSeasonalityDestinations
    type: object
    properties:
      DestinationLocations:
        type: array
        items:
          "$ref": "#/definitions/DestinationLocation"
      Links:
        type: array
        items:
          "$ref": "#/definitions/Link"
  Countries:
    title: Countries
    type: object
    properties:
      PointOfSale:
        description: ''
        type: string
      OriginCountries:
        description: ''
        type: array
        items:
          "$ref": "#/definitions/OriginCountry"
      DestinationCountries:
        description: ''
        type: array
        items:
          "$ref": "#/definitions/DestinationCountry"
      Links:
        description: ''
        type: array
        items:
          "$ref": "#/definitions/Link"
  CityPairOriginsdestinations:
    title: CityPairOriginsdestinations
    type: object
    properties:
      OriginDestinationLocations:
        type: array
        items:
          "$ref": "#/definitions/CityPairs"
      Links:
        type: array
        items:
          "$ref": "#/definitions/Link"
  Country:
    title: Country
    type: object
    properties:
      CountryCode:
        description: ''
        type: string
      CountryName:
        description: ''
        type: string
      Links:
        description: ''
        type: array
        items:
          "$ref": "#/definitions/Link"
  OriginCountry:
    title: OriginCountry
    type: object
    properties:
      CountryCode:
        description: ''
        type: string
      CountryName:
        description: ''
        type: string
  DestinationCountry:
    title: DestinationCountry
    type: object
    properties:
      CountryCode:
        description: ''
        type: string
      CountryName:
        description: ''
        type: string
  DestinationLocation:
    title: DestinationLocation
    type: object
    properties:
      AirportCode:
        type: string
      AirportName:
        type: string
      CityName:
        type: string
      CountryCode:
        type: string
      CountryName:
        type: string
      RegionName:
        type: string
  Link:
    title: Link
    type: object
    properties:
      rel:
        description: ''
        type: string
      href:
        description: ''
        type: string
  CityPairs:
    title: CityPairs
    type: object
    properties:
      OriginDestinationLocations:
        type: string
      OriginLocation:
        type: object
        properties:
          AirportCode:
            type: string
          AirportName:
            type: string
          CityName:
            type: string
          CountryCode:
            type: string
          CountryName:
            type: string
          RegionName:
            type: string
      DestinationLocation:
        type: object
        properties:
          AirportCode:
            type: string
          AirportName:
            type: string
          CityName:
            type: string
          CountryCode:
            type: string
          CountryName:
            type: string
          RegionName:
            type: string
